name:Face_recognition_app
channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv-python-headless
     - face_recognition
     -twilio
     -imutils
     -aioice


    
